name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

     # üí• FINAL ATTEMPT: BYPASSING THE ACTION WITH RAW DOCKER CLI
      - name: Login to Docker Hub using Raw CLI
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin
          
      # üèóÔ∏è Build and push FRONTEND image
      - name: Build and push frontend image.
        uses: docker/build-push-action@v6
        with:
          context: ./ocsreact
          file: ./ocsreact/Dockerfile
          push: true
          tags: |
            roygicheru/ocsfullstack-frontend:latest
            roygicheru/ocsfullstack-frontend:${{ github.run_number }}

      # ‚öôÔ∏è Build and push BACKEND image
      - name: Build and push backend image.
        uses: docker/build-push-action@v6
        with:
          context: ./ocsspring
          file: ./ocsspring/Dockerfile
          push: true
          tags: |
            roygicheru/ocsfullstack-backend:latest
            roygicheru/ocsfullstack-backend:${{ github.run_number }}
        # This is just a comment